IMPLEMENT_SIMPLE_AUTOMATION_TEST(FPlayerSerializationTest2, "Serialization.Player2", EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter)
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FPlayerSerializationTest3, "Serialization.Player2", EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter)
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FPlayerSerializationTest5, "Serialization.Player5", EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter)
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FPlayerSerializationTest6, "Serialization.Player6", EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter)
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FPlayerSerializationTest7, "Serialization.Player7", EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter)
